FROM $DOCKER_REPO/ubuntu:16.04

# For node optimisation
ENV NODE_ENV=production

# Install essentials
RUN apt-get update && \
	apt-get install -y \
		curl \
		build-essential \
		ca-certificates \
		gcc \
		git \
		libpq-dev \
		make \
		python-pip \
		python2.7 \
		python2.7-dev \
		ssh

# Install nginx
RUN apt-get install -y nginx

# Configure nginx
RUN chown -R www-data:www-data /var/lib/nginx

# Install node
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
	apt-get install -y nodejs

# Cleanup
RUN apt-get autoremove
RUN apt-get clean

# Environment variables
ENV SERVICE_PORT 8085

# Copying nginx config files
COPY nginx/service.nginx.conf /etc/nginx/servers/ecs-service
COPY nginx/container.nginx.conf /etc/nginx/nginx.conf

# Copying node application files
COPY package.json .
COPY package-lock.json .
COPY src src
COPY server.js .
COPY worker.js .

# Installing node dependencies
RUN npm install
EXPOSE 80

# Starting nginx and node server
COPY start.sh .
CMD ["bash", "start.sh"]
