FROM $DOCKER_REPO/node:carbon

COPY package.json .
RUN npm install

COPY index.js .
COPY config config
COPY lib lib
ENV PWG_LOAD_BALANCER=internal-ecs-lb-pwg-pvt-555364892.ap-southeast-1.elb.amazonaws.com


COPY src src
COPY server.js .
COPY worker.js .

EXPOSE 80

CMD [ "npm", "start" ]
